#!/usr/bin/env bash
# this script accepts an argument and ping the IP 5 times.

numArgs="$#";

if [ $numArgs == 0 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 $1
fi

