#!/usr/bin/env bash
# This script displays the text "Best School" 10 times, 
# but for the 9th iteration, it displays "Best School" and then
# "Hi" on a new line

counter=1
while [ $counter -le  10 ]
do
    echo "Best School"
    ((counter++))
    if [ $counter == 10 ]
    then
        echo "Hi"
    fi
done;
