#!/usr/bin/env bash
# This script displays Best School 10 times, but for the 9th iteration,
# displays Best School and then Hi on a new line.

counter=0
while [ $counter -le 10 ]
do
	if [ $counter -ne 9 ]
	then
		echo "Best School"
	else
		echo "Hi"
	fi
	(( counter++ ))
done
