#!/usr/bin/env bash
# this script displays the time for 12 hours and 59 minutes

minutes=1
hour=0
while [ $hour -lt 13 ]
do
    echo "Hour: $hour"
    while [ $minutes -lt 60 ]
    do
        echo "$minutes"
        ((minutes++))
    done;
    minutes=1
    ((hour++))
        
done;