#!/usr/bin/env bash
# this script displays the time for 12 hours and 59 minutes

counter=1
hour=0
while [ $hour -lt 12 ]
do
    echo "Hour: $hour"
    while [ $counter -lt 60 ]
    do
        echo "$counter"
        ((counter++))
    done;
    counter=1
    ((hour++))
        
done;
