#!/usr/bin/env bash
# this script displays the content of the current directory
# in alist format
# where only the part of the name after the first dash is displayed.

for file in *;
do
    dash=${file#*-}
    echo "$dash"
done;
